// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.atracer.model;

import org.atracer.model.PackageVersionDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PackageVersionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PackageVersionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PackageVersionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PackageVersionIntegrationTest: @Transactional;
    
    @Autowired
    private PackageVersionDataOnDemand PackageVersionIntegrationTest.dod;
    
    @Test
    public void PackageVersionIntegrationTest.testCountPackageVersions() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", dod.getRandomPackageVersion());
        long count = org.atracer.model.PackageVersion.countPackageVersions();
        org.junit.Assert.assertTrue("Counter for 'PackageVersion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PackageVersionIntegrationTest.testFindPackageVersion() {
        org.atracer.model.PackageVersion obj = dod.getRandomPackageVersion();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to provide an identifier", id);
        obj = org.atracer.model.PackageVersion.findPackageVersion(id);
        org.junit.Assert.assertNotNull("Find method for 'PackageVersion' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PackageVersion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PackageVersionIntegrationTest.testFindAllPackageVersions() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", dod.getRandomPackageVersion());
        long count = org.atracer.model.PackageVersion.countPackageVersions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PackageVersion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.atracer.model.PackageVersion> result = org.atracer.model.PackageVersion.findAllPackageVersions();
        org.junit.Assert.assertNotNull("Find all method for 'PackageVersion' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PackageVersion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PackageVersionIntegrationTest.testFindPackageVersionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", dod.getRandomPackageVersion());
        long count = org.atracer.model.PackageVersion.countPackageVersions();
        if (count > 20) count = 20;
        java.util.List<org.atracer.model.PackageVersion> result = org.atracer.model.PackageVersion.findPackageVersionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PackageVersion' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PackageVersion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PackageVersionIntegrationTest.testFlush() {
        org.atracer.model.PackageVersion obj = dod.getRandomPackageVersion();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to provide an identifier", id);
        obj = org.atracer.model.PackageVersion.findPackageVersion(id);
        org.junit.Assert.assertNotNull("Find method for 'PackageVersion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPackageVersion(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PackageVersion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PackageVersionIntegrationTest.testMerge() {
        org.atracer.model.PackageVersion obj = dod.getRandomPackageVersion();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to provide an identifier", id);
        obj = org.atracer.model.PackageVersion.findPackageVersion(id);
        boolean modified =  dod.modifyPackageVersion(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.atracer.model.PackageVersion merged = (org.atracer.model.PackageVersion) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PackageVersion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PackageVersionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", dod.getRandomPackageVersion());
        org.atracer.model.PackageVersion obj = dod.getNewTransientPackageVersion(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PackageVersion' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PackageVersion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PackageVersionIntegrationTest.testRemove() {
        org.atracer.model.PackageVersion obj = dod.getRandomPackageVersion();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageVersion' failed to provide an identifier", id);
        obj = org.atracer.model.PackageVersion.findPackageVersion(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PackageVersion' with identifier '" + id + "'", org.atracer.model.PackageVersion.findPackageVersion(id));
    }
    
}
