// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.atracer.model;

import java.util.List;
import java.util.Random;
import org.atracer.model.PackageVersion;
import org.springframework.stereotype.Component;

privileged aspect PackageVersionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PackageVersionDataOnDemand: @Component;
    
    private Random PackageVersionDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PackageVersion> PackageVersionDataOnDemand.data;
    
    public PackageVersion PackageVersionDataOnDemand.getNewTransientPackageVersion(int index) {
        org.atracer.model.PackageVersion obj = new org.atracer.model.PackageVersion();
        obj.setName("name_" + index);
        return obj;
    }
    
    public PackageVersion PackageVersionDataOnDemand.getSpecificPackageVersion(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PackageVersion obj = data.get(index);
        return PackageVersion.findPackageVersion(obj.getId());
    }
    
    public PackageVersion PackageVersionDataOnDemand.getRandomPackageVersion() {
        init();
        PackageVersion obj = data.get(rnd.nextInt(data.size()));
        return PackageVersion.findPackageVersion(obj.getId());
    }
    
    public boolean PackageVersionDataOnDemand.modifyPackageVersion(PackageVersion obj) {
        return false;
    }
    
    public void PackageVersionDataOnDemand.init() {
        data = org.atracer.model.PackageVersion.findPackageVersionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PackageVersion' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.atracer.model.PackageVersion>();
        for (int i = 0; i < 10; i++) {
            org.atracer.model.PackageVersion obj = getNewTransientPackageVersion(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
