// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.atracer.model;

import org.atracer.model.PackageNameDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PackageNameIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PackageNameIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PackageNameIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PackageNameIntegrationTest: @Transactional;
    
    @Autowired
    private PackageNameDataOnDemand PackageNameIntegrationTest.dod;
    
    @Test
    public void PackageNameIntegrationTest.testCountPackageNames() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", dod.getRandomPackageName());
        long count = org.atracer.model.PackageName.countPackageNames();
        org.junit.Assert.assertTrue("Counter for 'PackageName' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PackageNameIntegrationTest.testFindPackageName() {
        org.atracer.model.PackageName obj = dod.getRandomPackageName();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to provide an identifier", id);
        obj = org.atracer.model.PackageName.findPackageName(id);
        org.junit.Assert.assertNotNull("Find method for 'PackageName' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PackageName' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PackageNameIntegrationTest.testFindAllPackageNames() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", dod.getRandomPackageName());
        long count = org.atracer.model.PackageName.countPackageNames();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PackageName', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.atracer.model.PackageName> result = org.atracer.model.PackageName.findAllPackageNames();
        org.junit.Assert.assertNotNull("Find all method for 'PackageName' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PackageName' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PackageNameIntegrationTest.testFindPackageNameEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", dod.getRandomPackageName());
        long count = org.atracer.model.PackageName.countPackageNames();
        if (count > 20) count = 20;
        java.util.List<org.atracer.model.PackageName> result = org.atracer.model.PackageName.findPackageNameEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PackageName' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PackageName' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PackageNameIntegrationTest.testFlush() {
        org.atracer.model.PackageName obj = dod.getRandomPackageName();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to provide an identifier", id);
        obj = org.atracer.model.PackageName.findPackageName(id);
        org.junit.Assert.assertNotNull("Find method for 'PackageName' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPackageName(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PackageName' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PackageNameIntegrationTest.testMerge() {
        org.atracer.model.PackageName obj = dod.getRandomPackageName();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to provide an identifier", id);
        obj = org.atracer.model.PackageName.findPackageName(id);
        boolean modified =  dod.modifyPackageName(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.atracer.model.PackageName merged = (org.atracer.model.PackageName) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PackageName' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PackageNameIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", dod.getRandomPackageName());
        org.atracer.model.PackageName obj = dod.getNewTransientPackageName(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PackageName' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PackageName' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PackageNameIntegrationTest.testRemove() {
        org.atracer.model.PackageName obj = dod.getRandomPackageName();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PackageName' failed to provide an identifier", id);
        obj = org.atracer.model.PackageName.findPackageName(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PackageName' with identifier '" + id + "'", org.atracer.model.PackageName.findPackageName(id));
    }
    
}
