// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.atracer.model;

import java.lang.String;

privileged aspect PackageVersion_Roo_JavaBean {
    
    public String PackageVersion.getVersion() {
        return this.version;
    }
    
    public void PackageVersion.setVersion(String version) {
        this.version = version;
    }
    
}
