// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.atracer.model;

import java.lang.String;

privileged aspect PackageVersion_Roo_ToString {
    
    public String PackageVersion.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Version: ").append(getVersion());
        return sb.toString();
    }
    
}
